### ISSUE TITLE
[8.0/9.0] Is This A Complete Example Of An Odoo/Ionic Framework App?

### ISSUE THREAD

**Issue by lukebranch** [hparfr/odoo-ionic-sample#5]
@hparfr ,

Thank you for your initiative on this. My apologies for using the github issues to ask a question, I am just not sure how else to get in touch with you directly.

I'd like to ask if this is targeting the Odoo 8.0 or 9.0 branch, as well as enquire with you as to whether this is a complete example of an Odoo/Ionic App.

I'm currently looking for the right framework to build our own Odoo app, and would like to take a look at how you've done things to see what I can learn from your project.

If you have time please let me know whether this is a complete example of an Odoo/Ionic app, or if it is still a partially developed app, as I would like to know a bit more about the project before I dive into your code to learn what you've done so far.

**Comment by hparfr** [comment]
> I am just not sure how else to get in touch with you directly.

I'm not good at writing README.md or Contributors.md  :)

This has been tested against Odoo 8 (and OpenERP 7).
It's an example app. It's like Odoo : it works out of the box but it's barely usable unless you customize it.

It shows the list of MPR products to be made and let the user mark some of them as done. It can be a good start for developping an MRP related app with Ionic/Angular. 

It requires the modules [prodoo](https://github.com/akretion/odooapps/tree/prodoo_get_sale_from_procurement/prodoo) and [synchronizer](https://github.com/akretion/synchronizer)

> I'm currently looking for the right framework to build our own Odoo app

For Odoo "apps", we have experience with Angular 1.x and Ionic+Angular (Ionic is well suited for Tablet or desktop with touchscreen). Form my experience : It's way better (quicker to code and better structured) than Backbone apps (like the P.O.S. of Odoo).

If you go with Angular, you can benefit from our JSON-RPC layer : [angular-odoo](http://github.com/akretion/angular-odoo/).

**Comment by lukebranch** [comment]
@hparfr ,

Awesome, thanks for your help! I'll dig into the code over the next few weeks to learn from what you've done so far.
