### ISSUE TITLE
XMLHttpRequest cannot load http://localhost:8088/web/webclient/version_info

### ISSUE THREAD

**Issue by thantshweaung** [hparfr/odoo-ionic-sample#6]
Below error is occurred when login to odoo server. How can I solve it? If it because of CORS, how can I config in local odoo server without using nginx? Thanks.

> XMLHttpRequest cannot load http://localhost:8088/web/webclient/version_info. Response to preflight request doesn't pass access control check: A wildcard '*' cannot be used in the 'Access-Control-Allow-Origin' header when the credentials flag is true. Origin 'http://localhost:8100' is therefore not allowed access. The credentials mode of an XMLHttpRequest is controlled by the withCredentials attribute.
> app.js:23 error :  Object {title: "http", fullTrace: Object, message: "HTTP Error"}

**Comment by hparfr** [comment]
Thanks to nginx or apache you can set up a proxy to let the browser think she communicate with only one server. With that way, it will be valid from the same origin policy.

If you don't want a proxy, you can indeed serve your JS application from Odoo. It's how the Point of Sale (backbone app) is served.

From my experience, it's much confortable to develop with a proxy.
https://github.com/hparfr/odoo-ionic-sample/blob/master/www/README.md
