### ISSUE TITLE
Is there any version of odoo-ionic2 app

### ISSUE THREAD

**Issue by vaibsVB** [hparfr/odoo-ionic-sample#7]
I have just gone through `odoo-ionic-sample` but yet not implemented because I want to do same with `ionic2`. I apologies for creating issue to ask a question, I am not able to find how to get in contact with you.

I'd like to ask now with `Angular2`, ionic community also moving to `ionic2`, so is there any plan to look for `ionic2-odoo` app. I am eagerly waiting for ionic2-odoo app by you. I tried to convert `jquery` code to `ionic2` but there is no success and having `CORS` and `JSONP` issues.

Thanks in Advance

**Comment by hparfr** [comment]
I'm ok with issues for asking questions :)

About Angular2 / Ionic, I'm planning to work on it in the few months. I'm waiting AngularJS2 to be released before starting any dev on it. And new projects from my clients.

**Comment by vaibsVB** [comment]
Thanks for immediate reply. It will be glad if `ionic2-odoo` app released soon.

Till then can you help me out of this in `angular2/ionic2` code..

I have this piece of `jQuery` code that works fine cross-origin:

```
jQuery.ajax({
    url: "http://example.appspot.com/rest/app",
    type: "POST",        
    dataType: 'jsonp',
    jsonp: 'jsonp',
    data: JSON.stringify({"foo":"bar"}),
    contentType: "application/json; charset=utf-8",
    success: function (response) {
        console.log("success");
    },
    error: function (response) {
        console.log("failed");
    }
});
```

I'm a novice to ionic2. I'm trying to convert this to `Angular2/ionic2` code but there is no success.

Is there any similar function for `jquery.ajax` in `angular2/ionic2`. 
I'm not getting how to deal with the above code in `angular2/ionic2` using `this.http.get` or this.`http.post` or `this.jsonp.request`.

Any help appreciated.

Thanks in advance.

**Comment by hparfr** [comment]
If you don't want to have issues with CORS, I suggest you to serve your JS code from the same server as odoo. 

The easiest way is to put your app in a odoo module and access it through http://odooserver/mymodule/static/html/)

With angular it's best to use $http instead of jQuery.ajax

You can also use angular-odoo library for all your odoo requests

**Comment by vaibsVB** [comment]
Thanks `hparfr` I will try this for sure.
